export const authoritySurfacePublicData = {
  surfaces: [
    {
      id: 'home-root',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'hub',
      href: '/{locale}',
      title: {
        en: 'Homepage Root Hub',
        zh: '首页总入口',
      },
      description: {
        en: 'The root page must route discovery into curated collections, official tools, solutions, and installation guidance.',
        zh: '首页必须把发现流量导向精选合集、官方工具、solutions 和安装文档。',
      },
      placements: ['report', 'collections', 'skills', 'solutions', 'docs'],
    },
    {
      id: 'collections-hub',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'hub',
      href: '/{locale}/collections',
      title: {
        en: 'Collections Hub',
        zh: 'Collections 总入口',
      },
      description: {
        en: 'Browse curated collections for trusted tools, workflows, and practical next steps.',
        zh: '浏览精选合集，快速找到可信工具、工作流组合和清晰的下一步。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-official-trusted-tools',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-official-ai-skills-trusted-tools',
      title: {
        en: 'Official AI Skills & Trusted Tools',
        zh: '官方 AI Skills 与可信工具',
      },
      description: {
        en: 'A high-trust collection that lets the site lead with official and strongly verified ecosystems instead of random long-tail repos.',
        zh: '这是高信任合集，能让站点优先展示官方和强验证生态，而不是随机的长尾仓库。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-agent-workflows',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-agent-workflow-building-tools',
      title: {
        en: 'Agent Workflow Building Tools',
        zh: 'Agent 工作流构建工具',
      },
      description: {
        en: 'A curated collection for building multi-step agent workflows with clearer tool selection and execution paths.',
        zh: '面向多步 Agent 工作流的精选合集，帮助你更快选择合适工具并进入执行路径。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-claude-code',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-claude-code-skills',
      title: {
        en: 'Top Claude Code Skills',
        zh: '顶级 Claude Code Skills',
      },
      description: {
        en: 'A curated Claude Code collection for teams exploring installable tools, workflow helpers, and day-to-day developer tasks.',
        zh: '面向 Claude Code 团队的精选合集，适合探索可安装工具、工作流辅助能力与日常开发任务。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-cursor',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-cursor-compatible-skills-workflow-integrations',
      title: {
        en: 'Cursor-Compatible Skills',
        zh: 'Cursor 兼容 Skills',
      },
      description: {
        en: 'A clean surface for editor-specific demand with explicit workflow intent.',
        zh: '这是编辑器型需求的干净入口，能够明确承接 workflow intent。',
      },
      placements: ['skills', 'solutions'],
    },
    {
      id: 'collection-windsurf',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-windsurf-skills',
      title: {
        en: 'Top Windsurf Skills',
        zh: '顶级 Windsurf Skills',
      },
      description: {
        en: 'A platform collection that turns IDE demand into a stronger curated hub.',
        zh: '这是把 IDE 需求转成更强精选入口的平台合集。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-gemini',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-gemini-compatible-dev-tools-agent-workflow-skills',
      title: {
        en: 'Gemini Workflow Tools to Install First',
        zh: '优先安装的 Gemini 工作流工具',
      },
      description: {
        en: 'A Gemini-specific collection that turns compatibility research into a curated install path for real delivery teams.',
        zh: '这是 Gemini 场景下的精选合集，把兼容性研究导向更清晰的安装路径，适合真实交付团队。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-opencode',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-opencode-workflow-tools-companion-integrations',
      title: {
        en: 'OpenCode Workflow Tools to Install First',
        zh: '优先安装的 OpenCode 工作流工具',
      },
      description: {
        en: 'A focused OpenCode collection that shortens companion-tool selection before installation and rollout.',
        zh: '这是聚焦 OpenCode 的精选合集，帮助团队在安装和落地前更快收口 companion tool 选择。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-nextjs',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-nextjs-ai-tools-full-stack-developer-workflows',
      title: {
        en: 'Next.js Workflow Tools to Install First',
        zh: '优先安装的 Next.js 工作流工具',
      },
      description: {
        en: 'A full-stack workflow collection for Next.js teams that need a faster path from evaluation into install and rollout.',
        zh: '这是面向 Next.js 团队的全栈工作流合集，帮助用户更快从评估进入安装与落地。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-python',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-python-ai-agent-tools-developer-workflows',
      title: {
        en: 'Python Workflow Tools to Install First',
        zh: '优先安装的 Python 工作流工具',
      },
      description: {
        en: 'A Python engineering collection built for teams choosing installable workflow helpers instead of browsing raw packages.',
        zh: '这是面向 Python 工程团队的精选合集，帮助用户选择可安装的工作流工具，而不是继续浏览原始包列表。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-react',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-react-ai-tools-ui-workflows-component-development',
      title: {
        en: 'React Workflow Tools to Install First',
        zh: '优先安装的 React 工作流工具',
      },
      description: {
        en: 'A UI-focused React collection for teams comparing component, review, and interface workflow tools.',
        zh: '这是面向 UI 团队的 React 精选合集，适合比较组件、评审和界面工作流工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-typescript',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-typescript-ai-tools-developer-workflows',
      title: {
        en: 'TypeScript Workflow Tools to Install First',
        zh: '优先安装的 TypeScript 工作流工具',
      },
      description: {
        en: 'A typed-development collection that helps product teams shortlist TypeScript workflow tools with clear next steps.',
        zh: '这是面向类型化开发的精选合集，帮助产品团队更快筛出 TypeScript 工作流工具并进入下一步。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-rust',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-rust-ai-tools-systems-workflows-reliability',
      title: {
        en: 'Rust Workflow Tools to Install First',
        zh: '优先安装的 Rust 工作流工具',
      },
      description: {
        en: 'A systems-focused Rust collection for teams evaluating reliability, release, and guardrail workflows.',
        zh: '这是面向系统工程的 Rust 精选合集，适合评估可靠性、发布和护栏类工作流工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-devops',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-devops-operations-automation-tools',
      title: {
        en: 'DevOps Workflow Tools to Install First',
        zh: '优先安装的 DevOps 工作流工具',
      },
      description: {
        en: 'An operations-first collection for platform teams choosing release, incident, and automation helpers.',
        zh: '这是运维优先的精选合集，适合平台团队筛选发布、事故响应和自动化辅助工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-framework',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-frameworks-sdk-foundations-agents',
      title: {
        en: 'Agent Framework Tools to Install First',
        zh: '优先安装的 Agent Framework 工具',
      },
      description: {
        en: 'A framework and SDK collection for teams building agent foundations, not just browsing vendor names.',
        zh: '这是 framework 与 SDK 精选合集，适合搭建 agent 基础设施的团队，而不是只看厂商品牌名单。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-community',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-community-contributed-ai-agent-skills',
      title: {
        en: 'Community Skills to Install First',
        zh: '优先安装的 Community Skills',
      },
      description: {
        en: 'A community-tested collection for builders who want reusable skills without falling back to unfiltered repository browsing.',
        zh: '这是面向构建者的 community 精选合集，帮助用户找到可复用 skills，而不是回到无筛选的仓库浏览。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-productivity',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-productivity-tools-ai-enabled-developers',
      title: {
        en: 'AI Productivity Tools for Developers',
        zh: '开发者 AI 生产力工具',
      },
      description: {
        en: 'A practical collection around everyday execution gains instead of generic repository breadth.',
        zh: '这是围绕日常执行效率的实用合集，而不是泛泛的仓库覆盖。',
      },
      placements: ['home', 'collections'],
    },
    {
      id: 'solutions-hub',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'hub',
      href: '/{locale}/solutions',
      title: {
        en: 'Solutions Hub',
        zh: 'Solutions 总入口',
      },
      description: {
        en: 'Solutions pages bundle use-case demand into clearer action paths than open-ended directory browsing.',
        zh: 'Solutions 页面能把 use-case 需求整理成更清晰的行动路径，比开放式目录浏览更适合承接高意图流量。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'solution-agent-workflows',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/agent-workflows',
      title: {
        en: 'Agent Workflows Solution',
        zh: 'Agent 工作流方案页',
      },
      description: {
        en: 'A scenario page for users who already know the workflow problem they need to solve.',
        zh: '这是面向“已经知道自己要解决什么工作流问题”的用户的场景页。',
      },
      placements: ['home', 'skills', 'solutions'],
    },
    {
      id: 'solution-workflow-automation',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/workflow-automation',
      title: {
        en: 'Workflow Automation Solution',
        zh: '工作流自动化方案页',
      },
      description: {
        en: 'A use-case page for users searching for repeatable automation patterns instead of one-off tools.',
        zh: '这是为寻找“可复用自动化模式”而不是一次性工具的用户准备的场景页。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'solution-process-automation',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/process-automation',
      title: {
        en: 'Process Automation Solution',
        zh: '流程自动化方案页',
      },
      description: {
        en: 'A solution page for teams turning SOPs, handoffs, and operations into repeatable AI-assisted execution paths.',
        zh: '这是为 SOP、交接和运营流程寻找可复用 AI 执行路径的团队准备的方案页。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'solution-document-automation',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/document-automation',
      title: {
        en: 'Document Automation Solution',
        zh: '文档自动化方案页',
      },
      description: {
        en: 'A solution page for reports, PDFs, templates, and repeatable content delivery workflows.',
        zh: '这是面向报告、PDF、模板与可复用内容交付流程的方案页。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'solution-browser-automation',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/browser-automation',
      title: {
        en: 'Browser Automation Solution',
        zh: '浏览器自动化方案页',
      },
      description: {
        en: 'A solution page for web actions, browser agents, and repeatable site operations.',
        zh: '这是面向网页操作、浏览器 Agent 与可复用站点任务的方案页。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'solution-data-extraction',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/data-extraction',
      title: {
        en: 'Data Extraction Solution',
        zh: '数据提取方案页',
      },
      description: {
        en: 'A solution page for ETL, structured output, reporting pipelines, and data-heavy automation work.',
        zh: '这是为 ETL、结构化输出、报表管线和重数据自动化场景准备的方案页。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'docs-installation',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'guide',
      href: '/{locale}/docs/installation',
      title: {
        en: 'Installation Docs',
        zh: '安装文档',
      },
      description: {
        en: 'Step-by-step installation guidance for getting skills set up, validated, and ready to use.',
        zh: '逐步安装指南，帮助你完成配置、验证并尽快开始使用 skills。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'docs-cli-overview',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'guide',
      href: '/{locale}/docs/cli/overview',
      title: {
        en: 'CLI Overview Docs',
        zh: 'CLI 总览文档',
      },
      description: {
        en: 'A practical bridge into command behavior, sync rules, and what operators should validate after installation.',
        zh: '这是进入命令行为、同步规则和安装后验证动作的实操桥梁。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'blog-official-ai-agent-skills-guide',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'guide',
      href: '/{locale}/blog/official-ai-agent-skills-guide',
      title: {
        en: 'Official AI Agent Skills Guide',
        zh: '官方 AI Agent Skills 指南',
      },
      description: {
        en: 'An editorial guide that explains why certain skills are trusted and how to choose among them.',
        zh: '这是一篇编辑型指南，能解释为什么某些 skills 值得信任，以及该如何选择。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'blog-how-to-install-ai-agent-skills',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'guide',
      href: '/{locale}/blog/how-to-install-ai-agent-skills',
      title: {
        en: 'How to Install AI Agent Skills',
        zh: '如何安装 AI Agent Skills',
      },
      description: {
        en: 'A practical onboarding guide that bridges high-intent discovery into CLI and docs without forcing repository-level browsing first.',
        zh: '这是一篇实操型入门指南，可以把高意图流量直接交给 CLI 和文档，而不是先逼用户浏览 repo 级目录。',
      },
      placements: ['home', 'solutions'],
    },
    {
      id: 'blog-ide-comparison',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'comparison',
      href: '/{locale}/blog/claude-code-vs-cursor-vs-windsurf',
      title: {
        en: 'Claude Code vs Cursor vs Windsurf',
        zh: 'Claude Code vs Cursor vs Windsurf 对比',
      },
      description: {
        en: 'A practical comparison guide for choosing between Claude Code, Cursor, and Windsurf.',
        zh: '实用对比指南，帮助你在 Claude Code、Cursor 和 Windsurf 之间做选择。',
      },
      placements: ['home', 'skills', 'solutions'],
    },
    {
      id: 'blog-mcp-vs-rest-api',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'comparison',
      href: '/{locale}/blog/mcp-vs-rest-api-comparison',
      title: {
        en: 'MCP vs REST API Comparison',
        zh: 'MCP vs REST API 对比',
      },
      description: {
        en: 'A comparison guide that turns protocol intent into a strong editorial surface with practical evaluation context.',
        zh: '这是把协议型需求转成强编辑页的对比指南，适合承接更偏评估和选型的流量。',
      },
      placements: ['collections', 'solutions'],
    },
    {
      id: 'skills-directory',
      role: 'supporting',
      tier: 'P3',
      surfaceClass: 'directory',
      href: '/{locale}/skills',
      title: {
        en: 'Full Skills Directory',
        zh: '全量 Skills 目录',
      },
      description: {
        en: 'Browse the full skills directory when you want wider coverage after reviewing curated starting points.',
        zh: '在看过精选入口后，如果你还需要更广的覆盖范围，可以继续浏览完整 skills 目录。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
  ],
} as const;
