export const authoritySurfacePublicData = {
  surfaces: [
    {
      id: 'home-root',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'hub',
      href: '/{locale}',
      title: {
        en: 'Killer-Skills Homepage',
        zh: '首页总入口',
      },
      description: {
        en: 'Start with curated collections, official tools, solution pages, and installation guidance.',
        zh: '从精选合集、官方工具、场景方案和安装文档开始。',
      },
      placements: ['report', 'collections', 'skills', 'solutions', 'docs'],
    },
    {
      id: 'collections-hub',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'hub',
      href: '/{locale}/collections',
      title: {
        en: 'Skill Collections',
        zh: 'Collections 总入口',
      },
      description: {
        en: 'Browse curated collections for trusted tools, workflows, and clear setup paths.',
        zh: '浏览精选合集，快速找到可信工具、工作流组合和清晰安装路径。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-official-trusted-tools',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-official-ai-skills-trusted-tools',
      title: {
        en: 'Official AI Skills & Trusted Tools',
        zh: '官方 AI Skills 与可信工具',
      },
      description: {
        en: 'Start with official projects and established ecosystems before exploring broader community tools.',
        zh: '先查看官方项目和成熟生态，再继续探索更广泛的社区工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-agent-workflows',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-agent-workflow-building-tools',
      title: {
        en: 'Agent Workflow Building Tools',
        zh: 'Agent 工作流构建工具',
      },
      description: {
        en: 'A curated collection for building multi-step agent workflows with clearer tool selection and execution paths.',
        zh: '面向多步 Agent 工作流的精选合集，帮助你更快选择合适工具并进入执行路径。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-claude-code',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-claude-code-skills',
      title: {
        en: 'Top Claude Code Skills',
        zh: '顶级 Claude Code Skills',
      },
      description: {
        en: 'A curated Claude Code collection for teams exploring installable tools, workflow helpers, and day-to-day developer tasks.',
        zh: '面向 Claude Code 团队的精选合集，适合探索可安装工具、工作流辅助能力与日常开发任务。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-cursor',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-cursor-compatible-skills-workflow-integrations',
      title: {
        en: 'Cursor-Compatible Skills',
        zh: 'Cursor 兼容 Skills',
      },
      description: {
        en: 'A curated Cursor collection for editor-specific workflows with clear setup paths.',
        zh: '这是面向 Cursor 工作流的精选合集，适合按具体需求查找工具和安装路径。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-windsurf',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-windsurf-skills',
      title: {
        en: 'Top Windsurf Skills',
        zh: '顶级 Windsurf Skills',
      },
      description: {
        en: 'A Windsurf-focused collection for coding speed, rules sync, and team collaboration.',
        zh: '这是面向 Windsurf 的精选合集，聚焦编码提速、规则同步和团队协作。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-gemini',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-gemini-compatible-dev-tools-agent-workflow-skills',
      title: {
        en: 'Gemini Workflow Tools to Install First',
        zh: '优先安装的 Gemini 工作流工具',
      },
      description: {
        en: 'A Gemini-specific collection for coding support, rules sync, and installable workflow tools.',
        zh: '这是 Gemini 场景下的精选合集，聚焦编码支持、规则同步和可安装工作流工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-opencode',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-opencode-workflow-tools-companion-integrations',
      title: {
        en: 'OpenCode Workflow Tools to Install First',
        zh: '优先安装的 OpenCode 工作流工具',
      },
      description: {
        en: 'A focused OpenCode collection that shortens companion-tool selection before installation and team adoption.',
        zh: '这是聚焦 OpenCode 的精选合集，帮助团队在安装前更快筛选配套工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-nextjs',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-nextjs-ai-tools-full-stack-developer-workflows',
      title: {
        en: 'Next.js Workflow Tools to Install First',
        zh: '优先安装的 Next.js 工作流工具',
      },
      description: {
        en: 'A full-stack workflow collection for Next.js teams that want faster setup and team adoption.',
        zh: '这是面向 Next.js 团队的全栈工作流合集，帮助你更快完成安装并进入实际使用。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-python',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-python-ai-agent-tools-developer-workflows',
      title: {
        en: 'Python Workflow Tools to Install First',
        zh: '优先安装的 Python 工作流工具',
      },
      description: {
        en: 'A Python engineering collection built for teams choosing installable workflow helpers instead of browsing raw packages.',
        zh: '这是面向 Python 工程团队的精选合集，适合选择可安装的工作流工具，而不是继续浏览原始包列表。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-react',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-react-ai-tools-ui-workflows-component-development',
      title: {
        en: 'React Workflow Tools to Install First',
        zh: '优先安装的 React 工作流工具',
      },
      description: {
        en: 'A UI-focused React collection for teams comparing component, review, and interface workflow tools.',
        zh: '这是面向 UI 团队的 React 精选合集，适合比较组件、评审和界面工作流工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-typescript',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-typescript-ai-tools-developer-workflows',
      title: {
        en: 'TypeScript Workflow Tools to Install First',
        zh: '优先安装的 TypeScript 工作流工具',
      },
      description: {
        en: 'A typed-development collection that helps product teams shortlist TypeScript workflow tools with clear setup paths.',
        zh: '这是面向类型化开发的精选合集，帮助产品团队更快筛出 TypeScript 工作流工具和安装路径。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-rust',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-rust-ai-tools-systems-workflows-reliability',
      title: {
        en: 'Rust Workflow Tools to Install First',
        zh: '优先安装的 Rust 工作流工具',
      },
      description: {
        en: 'A systems-focused Rust collection for teams comparing reliability, release, and performance workflows.',
        zh: '这是面向系统工程的 Rust 精选合集，适合比较可靠性、发布和性能相关工作流工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-devops',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-devops-operations-automation-tools',
      title: {
        en: 'DevOps Workflow Tools to Install First',
        zh: '优先安装的 DevOps 工作流工具',
      },
      description: {
        en: 'An operations-first collection for platform teams choosing release, incident, and automation helpers.',
        zh: '这是运维优先的精选合集，适合平台团队筛选发布、事故响应和自动化辅助工具。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-framework',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-frameworks-sdk-foundations-agents',
      title: {
        en: 'Agent Framework Tools to Install First',
        zh: '优先安装的 Agent Framework 工具',
      },
      description: {
        en: 'A framework and SDK collection for teams building agent foundations, not just browsing vendor names.',
        zh: '这是 framework 与 SDK 精选合集，适合搭建 agent 基础设施的团队，而不是只看厂商品牌名单。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-community',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-community-contributed-ai-agent-skills',
      title: {
        en: 'Community Skills to Install First',
        zh: '优先安装的 Community Skills',
      },
      description: {
        en: 'A community-tested collection for builders who want reusable skills without falling back to unfiltered repository browsing.',
        zh: '这是面向构建者的 community 精选合集，适合查找可复用 skills，而不是回到无筛选的仓库浏览。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'collection-productivity',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'collection',
      href: '/{locale}/collections/top-productivity-tools-ai-enabled-developers',
      title: {
        en: 'AI Productivity Tools for Developers',
        zh: '开发者 AI 生产力工具',
      },
      description: {
        en: 'A practical collection around everyday execution gains instead of generic repository breadth.',
        zh: '这是围绕日常执行效率的实用合集，而不是泛泛的仓库覆盖。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'solutions-hub',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'hub',
      href: '/{locale}/solutions',
      title: {
        en: 'Workflow Solutions',
        zh: 'Solutions 总入口',
      },
      description: {
        en: 'Solution pages group common use cases so you can compare relevant skills faster.',
        zh: 'Solutions 页面按常见使用场景组织内容，帮助你更快比较相关 skills。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'solution-agent-workflows',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/agent-workflows',
      title: {
        en: 'Agent Workflows Solution',
        zh: 'Agent 工作流方案页',
      },
      description: {
        en: 'A scenario page for teams that already know the workflow problem they need to solve.',
        zh: '这是面向“已经知道自己要解决什么工作流问题”的团队场景页。',
      },
      placements: ['home', 'skills', 'solutions'],
    },
    {
      id: 'solution-workflow-automation',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/workflow-automation',
      title: {
        en: 'Workflow Automation Solution',
        zh: '工作流自动化方案页',
      },
      description: {
        en: 'A use-case page for repeatable automation patterns instead of one-off tools.',
        zh: '这是面向“可复用自动化模式”而不是一次性工具的场景页。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'solution-process-automation',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/process-automation',
      title: {
        en: 'Process Automation Solution',
        zh: '流程自动化方案页',
      },
      description: {
        en: 'A solution page for teams turning SOPs, shared workflows, and operations into repeatable AI-assisted execution paths.',
        zh: '这是为 SOP、协作流程和运营流程寻找可复用 AI 执行路径的团队准备的方案页。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'solution-document-automation',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/document-automation',
      title: {
        en: 'Document Automation Solution',
        zh: '文档自动化方案页',
      },
      description: {
        en: 'A solution page for reports, PDFs, templates, and repeatable content delivery workflows.',
        zh: '这是面向报告、PDF、模板与可复用内容交付流程的方案页。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'solution-browser-automation',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/browser-automation',
      title: {
        en: 'Browser Automation Solution',
        zh: '浏览器自动化方案页',
      },
      description: {
        en: 'A solution page for web actions, browser agents, and repeatable site operations.',
        zh: '这是面向网页操作、浏览器 Agent 与可复用站点任务的方案页。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'solution-data-extraction',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'solution',
      href: '/{locale}/solutions/data-extraction',
      title: {
        en: 'Data Extraction Solution',
        zh: '数据提取方案页',
      },
      description: {
        en: 'A solution page for ETL, structured output, reporting pipelines, and data-heavy automation work.',
        zh: '这是为 ETL、结构化输出、报表管线和重数据自动化场景准备的方案页。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'docs-installation',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'guide',
      href: '/{locale}/docs/installation',
      title: {
        en: 'Installation Docs',
        zh: '安装文档',
      },
      description: {
        en: 'Step-by-step installation guidance for getting skills set up and ready to use.',
        zh: '逐步安装指南，帮助你完成配置并尽快开始使用 skills。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'docs-cli-overview',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'guide',
      href: '/{locale}/docs/cli/overview',
      title: {
        en: 'CLI Overview Docs',
        zh: 'CLI 总览文档',
      },
      description: {
        en: 'Learn command behavior, sync rules, and what to check after installation.',
        zh: '了解命令行为、同步规则，以及安装后需要检查的内容。',
      },
      placements: ['home', 'collections', 'solutions'],
    },
    {
      id: 'blog-official-ai-agent-skills-guide',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'guide',
      href: '/{locale}/blog/official-ai-agent-skills-guide',
      title: {
        en: 'Official AI Agent Skills Guide',
        zh: '官方 AI Agent Skills 指南',
      },
      description: {
        en: 'A practical guide for choosing official and well-maintained AI agent skills.',
        zh: '这是一篇实用指南，帮助你选择官方和维护良好的 AI Agent Skills。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
    {
      id: 'blog-how-to-install-ai-agent-skills',
      role: 'primary',
      tier: 'P1',
      surfaceClass: 'guide',
      href: '/{locale}/blog/how-to-install-ai-agent-skills',
      title: {
        en: 'How to Install AI Agent Skills',
        zh: '如何安装 AI Agent Skills',
      },
      description: {
        en: 'A practical onboarding guide for moving from install commands into CLI and docs.',
        zh: '这是一篇实操型入门指南，适合从安装命令继续进入 CLI 和文档。',
      },
      placements: ['home', 'skills', 'solutions'],
    },
    {
      id: 'blog-ide-comparison',
      role: 'primary',
      tier: 'P0',
      surfaceClass: 'comparison',
      href: '/{locale}/blog/claude-code-vs-cursor-vs-windsurf',
      title: {
        en: 'Claude Code vs Cursor vs Windsurf',
        zh: 'Claude Code vs Cursor vs Windsurf 对比',
      },
      description: {
        en: 'A practical comparison guide for choosing between Claude Code, Cursor, and Windsurf.',
        zh: '实用对比指南，帮助你在 Claude Code、Cursor 和 Windsurf 之间做选择。',
      },
      placements: ['home', 'skills', 'solutions'],
    },
    {
      id: 'blog-mcp-vs-rest-api',
      role: 'primary',
      tier: 'P2',
      surfaceClass: 'comparison',
      href: '/{locale}/blog/mcp-vs-rest-api-comparison',
      title: {
        en: 'MCP vs REST API Comparison',
        zh: 'MCP vs REST API 对比',
      },
      description: {
        en: 'A comparison guide for choosing between MCP and REST API implementation paths.',
        zh: '这是一份对比指南，帮助团队在 MCP 与 REST API 实现路径之间做选择。',
      },
      placements: ['home', 'skills', 'collections'],
    },
    {
      id: 'skills-directory',
      role: 'supporting',
      tier: 'P3',
      surfaceClass: 'directory',
      href: '/{locale}/skills',
      title: {
        en: 'Full Skills Directory',
        zh: '全量 Skills 目录',
      },
      description: {
        en: 'Browse the full skills directory when you want wider coverage after checking curated starting points.',
        zh: '看过精选入口后，如果还需要更广的覆盖范围，可以继续浏览完整 skills 目录。',
      },
      placements: ['home', 'skills', 'collections', 'solutions'],
    },
  ],
} as const;
