name = "killer-skills"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ADMIN_USER = "admin_placeholder"

[[kv_namespaces]]
binding = "TRANSLATIONS"
id = "d5ab5c6705774d779d9b1342eda5f9ac"

[[kv_namespaces]]
binding = "SKILLS_CACHE"
id = "6130f39a06e14319b0ee4becb0d09842"

[[d1_databases]]
binding = "DB"
database_name = "killer-skills-db"
database_id = "4b51522f-2413-4df2-b7d3-ac1cb1f3ef32"

[[services]]
binding = "WORKFLOWS_SERVICE"
service = "killer-skills-workflows"

[[vectorize]]
binding = "VECTORIZE"
index_name = "killer-skills-search"

[ai]
binding = "AI"
