/**
 * 站点注册表 — 所有目标导航站的元信息
 *
 * 按梯队分组，Tier 1 = 长尾免费目录（全自动），Tier 2 = 中等权重（半自动），Tier 3 = 高权重（手动）
 */

import type { SiteConfig } from './types.js';

export const SITES: SiteConfig[] = [
    // ═══════════════════════════════════════════════════
    //  Tier 1 — 全自动（弱防御、纯表单）
    // ═══════════════════════════════════════════════════
    {
        id: 'tooldirs',
        name: 'ToolDirs',
        submitUrl: 'https://tooldirs.com/submit',
        homepage: 'https://tooldirs.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolnet',
        name: 'AI Tool NET',
        submitUrl: 'https://www.aitoolnet.com/submit',
        homepage: 'https://www.aitoolnet.com',
        estimatedDR: 25,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dropyourai',
        name: 'DropYourAI',
        submitUrl: 'https://dropyourai.com/submit-tool/',
        homepage: 'https://dropyourai.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aijumble',
        name: 'AiJumble',
        submitUrl: 'https://www.aijumble.com/submit',
        homepage: 'https://www.aijumble.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolindex',
        name: 'ToolIndex',
        submitUrl: 'https://toolindex.ai/submit',
        homepage: 'https://toolindex.ai',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aifinder',
        name: 'AI Finder',
        submitUrl: 'https://ai-finder.net/submit',
        homepage: 'https://ai-finder.net',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihub',
        name: 'AI Hub',
        submitUrl: 'https://aihub.fyi/submit',
        homepage: 'https://aihub.fyi',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'gptforge',
        name: 'GPT Forge',
        submitUrl: 'https://gptforge.net/submit',
        homepage: 'https://gptforge.net',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aicombined',
        name: 'AI Combined',
        submitUrl: 'https://aicombined.com/submit',
        homepage: 'https://aicombined.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'findcooltools',
        name: 'Find Cool Tools',
        submitUrl: 'https://findcool.tools/submit',
        homepage: 'https://findcool.tools',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'nextgentools',
        name: 'Next Gen Tools',
        submitUrl: 'https://nextgentools.me/submit',
        homepage: 'https://nextgentools.me',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'freeaitoolsdir',
        name: 'Free AI Tools Directory',
        submitUrl: 'https://free-ai-tools-directory.com/submit',
        homepage: 'https://free-ai-tools-directory.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aisearch',
        name: 'AI Search',
        submitUrl: 'https://ai-search.io/submit',
        homepage: 'https://ai-search.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'liveapps',
        name: 'Live Apps',
        submitUrl: 'https://liveapps.ai/submit',
        homepage: 'https://liveapps.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'balanai',
        name: 'Balan.ai',
        submitUrl: 'https://balan.ai/submit',
        homepage: 'https://balan.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dailytechai',
        name: 'Daily Tech AI',
        submitUrl: 'https://dailytech.ai/submit',
        homepage: 'https://dailytech.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'appcritica',
        name: 'AppCritica',
        submitUrl: 'https://appcritica.com/submit',
        homepage: 'https://appcritica.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'affordhunt',
        name: 'Afford Hunt',
        submitUrl: 'https://affordhunt.com/submit',
        homepage: 'https://affordhunt.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'devpages',
        name: 'Dev Pages',
        submitUrl: 'https://devpages.io/submit',
        homepage: 'https://devpages.io',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },

    // ═══════════════════════════════════════════════════
    //  Tier 2 — 半自动（需登录 / 基础验证码）
    // ═══════════════════════════════════════════════════
    {
        id: 'taaft',
        name: "There's An AI For That",
        submitUrl: 'https://theresanaiforthat.com/submit/',
        homepage: 'https://theresanaiforthat.com',
        estimatedDR: 60,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'futurepedia',
        name: 'Futurepedia',
        submitUrl: 'https://www.futurepedia.io/submit-tool',
        homepage: 'https://www.futurepedia.io',
        estimatedDR: 55,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'listmyai',
        name: 'ListMyAI',
        submitUrl: 'https://listmyai.net/submit',
        homepage: 'https://listmyai.net',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'alternativeto',
        name: 'AlternativeTo',
        submitUrl: 'https://alternativeto.net/add-app/',
        homepage: 'https://alternativeto.net',
        estimatedDR: 80,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'saashub',
        name: 'SaaSHub',
        submitUrl: 'https://www.saashub.com/submit',
        homepage: 'https://www.saashub.com',
        estimatedDR: 70,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'launchboosts',
        name: 'LaunchBoosts',
        submitUrl: 'https://launchboosts.com/submit',
        homepage: 'https://launchboosts.com',
        estimatedDR: 25,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: false,
    },
    {
        id: 'saasaitools',
        name: 'SaaS AI Tools',
        submitUrl: 'https://saasaitools.com/submit',
        homepage: 'https://saasaitools.com',
        estimatedDR: 35,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false,
    },
];
