/**
 * 站点注册表 — 所有目标导航站的元信息
 *
 * 按梯队分组，Tier 1 = 长尾免费目录（全自动），Tier 2 = 中等权重（半自动），Tier 3 = 高权重（手动）
 */

import type { SiteConfig } from './types.js';

export const SITES: SiteConfig[] = [
    // ═══════════════════════════════════════════════════
    //  Tier 1 — 全自动（弱防御、纯表单、近期发现的新站）
    // ═══════════════════════════════════════════════════
    {
        id: 'technologyreview',
        name: 'Technology Review (MIT)',
        submitUrl: 'https://www.technologyreview.com/submit',
        homepage: 'https://www.technologyreview.com/',
        estimatedDR: 90,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aivalley',
        name: 'AI Valley',
        submitUrl: 'https://aivalley.ai/submit',
        homepage: 'https://aivalley.ai',
        estimatedDR: 30,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aiagentsdirectory',
        name: 'AI Agents Directory',
        submitUrl: 'https://aiagentsdirectory.com/submit',
        homepage: 'https://aiagentsdirectory.com/',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aiwithme',
        name: 'AI With Me',
        submitUrl: 'https://aiwith.me/submit',
        homepage: 'https://aiwith.me/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolwave',
        name: 'ToolWave',
        submitUrl: 'https://www.toolwave.io/submit',
        homepage: 'https://www.toolwave.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aipulse',
        name: 'AI Pulse',
        submitUrl: 'https://www.aipulse.fyi/submit',
        homepage: 'https://www.aipulse.fyi',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'listyourtool',
        name: 'ListYourTool',
        submitUrl: 'https://www.listyourtool.com/submit',
        homepage: 'https://www.listyourtool.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'infrabase',
        name: 'InfraBase',
        submitUrl: 'https://infrabase.ai/submit',
        homepage: 'https://infrabase.ai/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'nocodelist',
        name: 'NoCodeList',
        submitUrl: 'https://nocodelist.co/submit',
        homepage: 'https://nocodelist.co',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'opentoolsai',
        name: 'OpenTools AI',
        submitUrl: 'https://opentools.ai/submit',
        homepage: 'https://opentools.ai/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'uneedbest',
        name: 'Uneed Best',
        submitUrl: 'https://www.uneed.best/submit',
        homepage: 'https://www.uneed.best/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'makerlist',
        name: 'MakerList',
        submitUrl: 'https://makerlist.io/submit',
        homepage: 'https://makerlist.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolsfyi',
        name: 'AI Tools FYI',
        submitUrl: 'https://aitools.fyi/submit',
        homepage: 'https://aitools.fyi',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolhouse',
        name: 'AI Tool House',
        submitUrl: 'https://www.aitoolhouse.com/submit',
        homepage: 'https://www.aitoolhouse.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolpilotai',
        name: 'ToolPilot AI',
        submitUrl: 'https://www.toolpilot.ai/submit',
        homepage: 'https://www.toolpilot.ai',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitool Scorner',
        name: 'AI Tools Corner',
        submitUrl: 'https://aitoolscorner.com/submit',
        homepage: 'https://aitoolscorner.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolslove',
        name: 'AI Tools Love',
        submitUrl: 'https://aitools.love/submit',
        homepage: 'https://aitools.love/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'whatisaitools',
        name: 'WhatIsAI.tools',
        submitUrl: 'https://whatisaitools.com/submit',
        homepage: 'https://whatisaitools.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'freeaitoolsfyi',
        name: 'Free AI Tools FYI',
        submitUrl: 'https://www.freeaitools.fyi/submit',
        homepage: 'https://www.freeaitools.fyi/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolboard',
        name: 'AI Tool Board',
        submitUrl: 'https://aitoolboard.com/submit',
        homepage: 'https://aitoolboard.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'journaliststoolbox',
        name: 'Journalists Toolbox',
        submitUrl: 'https://journaliststoolbox.ai/submit',
        homepage: 'https://journaliststoolbox.ai',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'buildvoyage',
        name: 'BuildVoyage',
        submitUrl: 'https://buildvoyage.com/submit',
        homepage: 'https://buildvoyage.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'lookaitools',
        name: 'LookAI Tools',
        submitUrl: 'https://lookaitools.com/submit',
        homepage: 'https://lookaitools.com/',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dangai',
        name: 'Dang.ai',
        submitUrl: 'https://dang.ai/submit', // 盲打发现可用
        homepage: 'https://dang.ai',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aidepot',
        name: 'AIDepot',
        submitUrl: 'https://aidepot.co/submit', // 盲打发现可用
        homepage: 'https://aidepot.co',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolnest',
        name: 'ToolNest',
        submitUrl: 'https://toolnest.ai/submit', // 盲打发现可用
        homepage: 'https://toolnest.ai',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolsguide',
        name: 'AIToolsGuide',
        submitUrl: 'https://aitoolsguide.com/submit', // 盲打发现可用
        homepage: 'https://aitoolsguide.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aimatch',
        name: 'AIMatch',
        submitUrl: 'https://aimatch.pro/submit', // 盲打发现可用
        homepage: 'https://aimatch.pro',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'paperswithcode',
        name: 'Papers With Code',
        submitUrl: 'https://paperswithcode.com/submit', // 盲打发现可用
        homepage: 'https://paperswithcode.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolspedia',
        name: 'Toolspedia',
        submitUrl: 'https://www.toolspedia.io/submit', // 盲打发现可用
        homepage: 'https://www.toolspedia.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihuntlist',
        name: 'AIHuntList',
        submitUrl: 'https://aihuntlist.com/submit', // 盲打发现可用
        homepage: 'https://aihuntlist.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolsdirectory',
        name: 'AIToolsDirectory',
        submitUrl: 'https://aitoolsdirectory.com/submit', // 盲打发现可用
        homepage: 'https://aitoolsdirectory.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'stratup',
        name: 'Stratup AI',
        submitUrl: 'https://stratup.ai/submit', // 盲打发现可用
        homepage: 'https://stratup.ai',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolslisttop',
        name: 'AIToolsList',
        submitUrl: 'https://www.aitoolslist.top/submit', // 盲打发现可用
        homepage: 'https://www.aitoolslist.top',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'flowtools',
        name: 'FlowTools',
        submitUrl: 'https://www.flowtools.co/submit', // 盲打发现可用
        homepage: 'https://www.flowtools.co',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolex',
        name: 'AIToolEx',
        submitUrl: 'https://aitoolex.com/submit', // 盲打发现可用
        homepage: 'https://aitoolex.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolpasta',
        name: 'ToolPasta',
        submitUrl: 'https://toolpasta.com/submit', // 盲打发现可用
        homepage: 'https://toolpasta.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aidirectoryorg',
        name: 'AIDirectory.org',
        submitUrl: 'https://www.aidirectory.org/submit', // 盲打发现可用
        homepage: 'https://www.aidirectory.org',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'startupbase',
        name: 'Startup Base',
        submitUrl: 'https://startupbase.io/submit', // 盲打发现可用
        homepage: 'https://startupbase.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolsaver',
        name: 'AI Tool Saver',
        submitUrl: 'https://www.aitoolsaver.com/submit', // 盲打发现可用
        homepage: 'https://www.aitoolsaver.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'madgenius',
        name: 'Mad Genius',
        submitUrl: 'https://madgenius.co/submit', // 盲打发现可用
        homepage: 'https://madgenius.co',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'flipbytes',
        name: 'FlipBytes',
        submitUrl: 'https://www.flipbytes.com/submit', // 盲打发现可用
        homepage: 'https://www.flipbytes.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'airespo',
        name: 'AI Respo',
        submitUrl: 'https://airespo.com/submit', // 盲打发现可用
        homepage: 'https://airespo.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    // ═══════════════════════════════════════════════════
    //  Tier 1 — 全自动（弱防御、纯表单）
    // ═══════════════════════════════════════════════════
    {
        id: 'tooldirs',
        name: 'ToolDirs',
        submitUrl: 'https://tooldirs.com/submit',
        homepage: 'https://tooldirs.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolnet',
        name: 'AI Tool NET',
        submitUrl: 'https://www.aitoolnet.com/submit',
        homepage: 'https://www.aitoolnet.com',
        estimatedDR: 25,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dropyourai',
        name: 'DropYourAI',
        submitUrl: 'https://dropyourai.com/submit-tool/',
        homepage: 'https://dropyourai.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aijumble',
        name: 'AiJumble',
        submitUrl: 'https://www.aijumble.com/submit',
        homepage: 'https://www.aijumble.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolindex',
        name: 'ToolIndex',
        submitUrl: 'https://toolindex.ai/submit',
        homepage: 'https://toolindex.ai',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aifinder',
        name: 'AI Finder',
        submitUrl: 'https://ai-finder.net/submit',
        homepage: 'https://ai-finder.net',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihub',
        name: 'AI Hub',
        submitUrl: 'https://aihub.fyi/submit',
        homepage: 'https://aihub.fyi',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'gptforge',
        name: 'GPT Forge',
        submitUrl: 'https://gptforge.net/submit',
        homepage: 'https://gptforge.net',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aicombined',
        name: 'AI Combined',
        submitUrl: 'https://aicombined.com/submit',
        homepage: 'https://aicombined.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'findcooltools',
        name: 'Find Cool Tools',
        submitUrl: 'https://findcool.tools/submit',
        homepage: 'https://findcool.tools',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'nextgentools',
        name: 'Next Gen Tools',
        submitUrl: 'https://nextgentools.me/submit',
        homepage: 'https://nextgentools.me',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'freeaitoolsdir',
        name: 'Free AI Tools Directory',
        submitUrl: 'https://free-ai-tools-directory.com/submit',
        homepage: 'https://free-ai-tools-directory.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aisearch',
        name: 'AI Search',
        submitUrl: 'https://ai-search.io/submit',
        homepage: 'https://ai-search.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'liveapps',
        name: 'Live Apps',
        submitUrl: 'https://liveapps.ai/submit',
        homepage: 'https://liveapps.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'balanai',
        name: 'Balan.ai',
        submitUrl: 'https://balan.ai/submit',
        homepage: 'https://balan.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dailytechai',
        name: 'Daily Tech AI',
        submitUrl: 'https://dailytech.ai/submit',
        homepage: 'https://dailytech.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'appcritica',
        name: 'AppCritica',
        submitUrl: 'https://appcritica.com/submit',
        homepage: 'https://appcritica.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'affordhunt',
        name: 'Afford Hunt',
        submitUrl: 'https://affordhunt.com/submit',
        homepage: 'https://affordhunt.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'devpages',
        name: 'Dev Pages',
        submitUrl: 'https://devpages.io/submit',
        homepage: 'https://devpages.io',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },

    // ═══════════════════════════════════════════════════
    //  Tier 2 — 半自动（需登录 / 基础验证码）
    // ═══════════════════════════════════════════════════
    {
        id: 'toolscout',
        name: 'ToolScout',
        submitUrl: 'https://toolscout.ai/submit',
        homepage: 'https://toolscout.ai',
        estimatedDR: 45,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'taaft',
        name: "There's An AI For That",
        submitUrl: 'https://theresanaiforthat.com/submit/',
        homepage: 'https://theresanaiforthat.com',
        estimatedDR: 60,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false, // ⚠️ 已变更为付费模式
    },
    {
        id: 'futurepedia',
        name: 'Futurepedia',
        submitUrl: 'https://www.futurepedia.io/submit-tool',
        homepage: 'https://www.futurepedia.io',
        estimatedDR: 55,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false, // ⚠️ 已变更为付费模式
    },
    {
        id: 'listmyai',
        name: 'ListMyAI',
        submitUrl: 'https://listmyai.net/submit',
        homepage: 'https://listmyai.net',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'alternativeto',
        name: 'AlternativeTo',
        submitUrl: 'https://alternativeto.net/add-app/',
        homepage: 'https://alternativeto.net',
        estimatedDR: 80,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
    {
        id: 'stackshare',
        name: 'StackShare',
        submitUrl: 'https://stackshare.io/submit',
        homepage: 'https://stackshare.io',
        estimatedDR: 70,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'saasscout',
        name: 'SaaS Scout',
        submitUrl: 'https://saasscout.io/submit-tool',
        homepage: 'https://saasscout.io',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'betalist',
        name: 'Betalist',
        submitUrl: 'https://betalist.com/submit',
        homepage: 'https://betalist.com',
        estimatedDR: 65,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
    {
        id: 'startupstash',
        name: 'StartupStash',
        submitUrl: 'https://startupstash.com/submit/',
        homepage: 'https://startupstash.com',
        estimatedDR: 70,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'launchingnext',
        name: 'LaunchingNext',
        submitUrl: 'https://www.launchingnext.com/submit/',
        homepage: 'https://www.launchingnext.com',
        estimatedDR: 60,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'startuppitch',
        name: 'The Startup Pitch',
        submitUrl: 'https://thestartuppitch.com/pitch-your-startup/',
        homepage: 'https://thestartuppitch.com',
        estimatedDR: 55,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'hackernews',
        name: 'Hacker News (Show HN)',
        submitUrl: 'https://news.ycombinator.com/show',
        homepage: 'https://news.ycombinator.com',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'futuretools',
        name: 'FutureTools.io',
        submitUrl: 'https://www.futuretools.io/submit-a-tool',
        homepage: 'https://www.futuretools.io',
        estimatedDR: 50,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'saashub',
        name: 'SaaSHub',
        submitUrl: 'https://www.saashub.com/submit',
        homepage: 'https://www.saashub.com',
        estimatedDR: 65,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aidirectory',
        name: 'AI Directory',
        submitUrl: 'https://aidirectory.com/submit',
        homepage: 'https://aidirectory.com',
        estimatedDR: 35,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aigems',
        name: 'AI Gems',
        submitUrl: 'https://aigems.net/submit',
        homepage: 'https://aigems.net',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dofollowtools',
        name: 'Dofollow.Tools',
        submitUrl: 'https://dofollow.tools/submit',
        homepage: 'https://dofollow.tools',
        estimatedDR: 25,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolify',
        name: 'Toolify.ai',
        submitUrl: 'https://www.toolify.ai/submit',
        homepage: 'https://www.toolify.ai',
        estimatedDR: 45,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false, // ⚠️ 付费模式 ($99)
    },
    {
        id: 'topaitools',
        name: 'TopAI.tools',
        submitUrl: 'https://topai.tools/submit',
        homepage: 'https://topai.tools',
        estimatedDR: 40,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false, // ⚠️ 付费模式 ($47)
    },
    {
        id: 'aireviewbattle',
        name: 'AI Review Battle',
        submitUrl: 'https://aireviewbattle.com/submit-tool/',
        homepage: 'https://aireviewbattle.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihunter',
        name: 'Ai-Hunter.io',
        submitUrl: 'https://ai-hunter.io/submit-tool/',
        homepage: 'https://ai-hunter.io',
        estimatedDR: 25,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aixploria',
        name: 'AIxploria',
        submitUrl: 'https://www.aixploria.com/submit-a-tool/',
        homepage: 'https://www.aixploria.com',
        estimatedDR: 30,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'sourceforge',
        name: 'SourceForge',
        submitUrl: 'https://sourceforge.net/create/',
        homepage: 'https://sourceforge.net',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'producthunt',
        name: 'Product Hunt',
        submitUrl: 'https://www.producthunt.com/posts/new',
        homepage: 'https://www.producthunt.com',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
];
