/**
 * 站点注册表 — 所有目标导航站的元信息
 *
 * 按梯队分组，Tier 1 = 长尾免费目录（全自动），Tier 2 = 中等权重（半自动），Tier 3 = 高权重（手动）
 */

import type { SiteConfig } from './types.js';

export const SITES: SiteConfig[] = [
    // ═══════════════════════════════════════════════════
    //  Tier 1 — 全自动（弱防御、纯表单）
    // ═══════════════════════════════════════════════════
    {
        id: 'tooldirs',
        name: 'ToolDirs',
        submitUrl: 'https://tooldirs.com/submit',
        homepage: 'https://tooldirs.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aitoolnet',
        name: 'AI Tool NET',
        submitUrl: 'https://www.aitoolnet.com/submit',
        homepage: 'https://www.aitoolnet.com',
        estimatedDR: 25,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dropyourai',
        name: 'DropYourAI',
        submitUrl: 'https://dropyourai.com/submit-tool/',
        homepage: 'https://dropyourai.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aijumble',
        name: 'AiJumble',
        submitUrl: 'https://www.aijumble.com/submit',
        homepage: 'https://www.aijumble.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolindex',
        name: 'ToolIndex',
        submitUrl: 'https://toolindex.ai/submit',
        homepage: 'https://toolindex.ai',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aifinder',
        name: 'AI Finder',
        submitUrl: 'https://ai-finder.net/submit',
        homepage: 'https://ai-finder.net',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihub',
        name: 'AI Hub',
        submitUrl: 'https://aihub.fyi/submit',
        homepage: 'https://aihub.fyi',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'gptforge',
        name: 'GPT Forge',
        submitUrl: 'https://gptforge.net/submit',
        homepage: 'https://gptforge.net',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aicombined',
        name: 'AI Combined',
        submitUrl: 'https://aicombined.com/submit',
        homepage: 'https://aicombined.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'findcooltools',
        name: 'Find Cool Tools',
        submitUrl: 'https://findcool.tools/submit',
        homepage: 'https://findcool.tools',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'nextgentools',
        name: 'Next Gen Tools',
        submitUrl: 'https://nextgentools.me/submit',
        homepage: 'https://nextgentools.me',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'freeaitoolsdir',
        name: 'Free AI Tools Directory',
        submitUrl: 'https://free-ai-tools-directory.com/submit',
        homepage: 'https://free-ai-tools-directory.com',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aisearch',
        name: 'AI Search',
        submitUrl: 'https://ai-search.io/submit',
        homepage: 'https://ai-search.io',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'liveapps',
        name: 'Live Apps',
        submitUrl: 'https://liveapps.ai/submit',
        homepage: 'https://liveapps.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'balanai',
        name: 'Balan.ai',
        submitUrl: 'https://balan.ai/submit',
        homepage: 'https://balan.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dailytechai',
        name: 'Daily Tech AI',
        submitUrl: 'https://dailytech.ai/submit',
        homepage: 'https://dailytech.ai',
        estimatedDR: 10,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'appcritica',
        name: 'AppCritica',
        submitUrl: 'https://appcritica.com/submit',
        homepage: 'https://appcritica.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'affordhunt',
        name: 'Afford Hunt',
        submitUrl: 'https://affordhunt.com/submit',
        homepage: 'https://affordhunt.com',
        estimatedDR: 15,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'devpages',
        name: 'Dev Pages',
        submitUrl: 'https://devpages.io/submit',
        homepage: 'https://devpages.io',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },

    // ═══════════════════════════════════════════════════
    //  Tier 2 — 半自动（需登录 / 基础验证码）
    // ═══════════════════════════════════════════════════
    {
        id: 'toolscout',
        name: 'ToolScout',
        submitUrl: 'https://toolscout.ai/submit',
        homepage: 'https://toolscout.ai',
        estimatedDR: 45,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'taaft',
        name: "There's An AI For That",
        submitUrl: 'https://theresanaiforthat.com/submit/',
        homepage: 'https://theresanaiforthat.com',
        estimatedDR: 60,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false, // ⚠️ 已变更为付费模式
    },
    {
        id: 'futurepedia',
        name: 'Futurepedia',
        submitUrl: 'https://www.futurepedia.io/submit-tool',
        homepage: 'https://www.futurepedia.io',
        estimatedDR: 55,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: false, // ⚠️ 已变更为付费模式
    },
    {
        id: 'listmyai',
        name: 'ListMyAI',
        submitUrl: 'https://listmyai.net/submit',
        homepage: 'https://listmyai.net',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false,
    },
    {
        id: 'alternativeto',
        name: 'AlternativeTo',
        submitUrl: 'https://alternativeto.net/add-app/',
        homepage: 'https://alternativeto.net',
        estimatedDR: 80,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
    {
        id: 'stackshare',
        name: 'StackShare',
        submitUrl: 'https://stackshare.io/submit',
        homepage: 'https://stackshare.io',
        estimatedDR: 70,
        tier: 2,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'saasscout',
        name: 'SaaS Scout',
        submitUrl: 'https://saasscout.io/submit-tool',
        homepage: 'https://saasscout.io',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'betalist',
        name: 'Betalist',
        submitUrl: 'https://betalist.com/submit',
        homepage: 'https://betalist.com',
        estimatedDR: 65,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
    {
        id: 'startupstash',
        name: 'StartupStash',
        submitUrl: 'https://startupstash.com/submit/',
        homepage: 'https://startupstash.com',
        estimatedDR: 70,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'launchingnext',
        name: 'LaunchingNext',
        submitUrl: 'https://www.launchingnext.com/submit/',
        homepage: 'https://www.launchingnext.com',
        estimatedDR: 60,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'startuppitch',
        name: 'The Startup Pitch',
        submitUrl: 'https://thestartuppitch.com/pitch-your-startup/',
        homepage: 'https://thestartuppitch.com',
        estimatedDR: 55,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'hackernews',
        name: 'Hacker News (Show HN)',
        submitUrl: 'https://news.ycombinator.com/show',
        homepage: 'https://news.ycombinator.com',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'futuretools',
        name: 'FutureTools.io',
        submitUrl: 'https://www.futuretools.io/submit-a-tool',
        homepage: 'https://www.futuretools.io',
        estimatedDR: 50,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'saashub',
        name: 'SaaSHub',
        submitUrl: 'https://www.saashub.com/submit',
        homepage: 'https://www.saashub.com',
        estimatedDR: 65,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aidirectory',
        name: 'AI Directory',
        submitUrl: 'https://aidirectory.com/submit',
        homepage: 'https://aidirectory.com',
        estimatedDR: 35,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aigems',
        name: 'AI Gems',
        submitUrl: 'https://aigems.net/submit',
        homepage: 'https://aigems.net',
        estimatedDR: 30,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'dofollowtools',
        name: 'Dofollow.Tools',
        submitUrl: 'https://dofollow.tools/submit',
        homepage: 'https://dofollow.tools',
        estimatedDR: 25,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'toolify',
        name: 'Toolify.ai',
        submitUrl: 'https://www.toolify.ai/submit',
        homepage: 'https://www.toolify.ai',
        estimatedDR: 45,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false, // ⚠️ 付费模式 ($99)
    },
    {
        id: 'topaitools',
        name: 'TopAI.tools',
        submitUrl: 'https://topai.tools/submit',
        homepage: 'https://topai.tools',
        estimatedDR: 40,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: true,
        enabled: false, // ⚠️ 付费模式 ($47)
    },
    {
        id: 'aireviewbattle',
        name: 'AI Review Battle',
        submitUrl: 'https://aireviewbattle.com/submit-tool/',
        homepage: 'https://aireviewbattle.com',
        estimatedDR: 20,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aihunter',
        name: 'Ai-Hunter.io',
        submitUrl: 'https://ai-hunter.io/submit-tool/',
        homepage: 'https://ai-hunter.io',
        estimatedDR: 25,
        tier: 2,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'aixploria',
        name: 'AIxploria',
        submitUrl: 'https://www.aixploria.com/submit-a-tool/',
        homepage: 'https://www.aixploria.com',
        estimatedDR: 30,
        tier: 1,
        requiresLogin: false,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'sourceforge',
        name: 'SourceForge',
        submitUrl: 'https://sourceforge.net/create/',
        homepage: 'https://sourceforge.net',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: false,
        enabled: true,
    },
    {
        id: 'producthunt',
        name: 'Product Hunt',
        submitUrl: 'https://www.producthunt.com/posts/new',
        homepage: 'https://www.producthunt.com',
        estimatedDR: 90,
        tier: 3,
        requiresLogin: true,
        hasCaptcha: true,
        enabled: true,
    },
];
