/**
 * Example IDE Adapter Plugin for Killer-Skills CLI
 * 
 * This plugin demonstrates how to add support for a custom IDE.
 */

import path from 'path';
import os from 'os';

/**
 * IDE Configuration
 */
export const config = {
    name: 'my-custom-ide',
    displayName: 'My Custom IDE',

    // Where skills should be installed
    skillsDir: path.join(os.homedir(), '.my-custom-ide', 'skills'),

    // Config file for AI prompts
    configFile: '.myide-rules',

    // Whether this IDE is currently installed/available
    isAvailable: () => {
        // Check if IDE is installed
        // return fs.existsSync('/path/to/ide');
        return true;
    }
};

/**
 * Generate prompt content for this IDE
 * @param {Array} skills - List of installed skills
 * @returns {string} - Formatted prompt content
 */
export function generatePrompt(skills) {
    const header = `# My Custom IDE - AI Skills Configuration
# Generated by Killer-Skills CLI
# Skills Count: ${skills.length}

`;

    const skillList = skills.map(skill => {
        return `## ${skill.name}
Description: ${skill.description}
Path: ${skill.path}
`;
    }).join('\n');

    return header + skillList;
}

/**
 * Install a skill for this IDE
 * @param {Object} skill - Skill to install
 * @param {string} targetPath - Target installation path
 */
export async function installSkill(skill, targetPath) {
    // Custom installation logic for this IDE
    console.log(`Installing ${skill.name} to ${targetPath}`);

    // Copy files, transform configs, etc.
}

/**
 * Get the prompt file path for this IDE
 * @returns {string} - Path to the prompt config file
 */
export function getPromptPath() {
    return path.join(os.homedir(), config.configFile);
}
