import { describe, expect, it } from 'vitest';
import { buildRecoveryExecutionQueueReport } from './recovery-execution-queue';

describe('buildRecoveryExecutionQueueReport', () => {
  it('creates ready, blocked, and watch lanes from control-board and scorecard truth', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'blocked',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-trailing_slash',
            lens: 'cluster',
            status: 'blocked',
            score: 6557.3,
            title: 'Issue cluster: trailing_slash',
            summary: 'High-confidence canonical trap.',
            evidence: ['trailing slash sample'],
            actions: ['Keep trailing-slash canonicalization at the edge.'],
          },
          {
            id: 'locale-decline-ja',
            lens: 'locale',
            status: 'recoverable',
            score: 32.5,
            title: 'Locale suppression: ja',
            summary: 'Locale lost clicks.',
            evidence: ['Current clicks 0'],
            actions: ['Inspect locale internal links.'],
          },
        ],
        nextActions: ['Keep trailing-slash canonicalization at the edge.'],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'blocking',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'Crawl is stable.',
          target: 'Stay clear.',
          observed: '1,650 checked.',
          notes: ['No regression.'],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 1650,
            discoveredUrls: 29280,
            sitemapFiles: 20,
            sitemapErrors: 0,
            status2xx: 1650,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'blocking',
          summary: 'Coverage source is stale.',
          target: 'Stay fresh.',
          observed: 'Freshest raw export 2026-04-03.',
          notes: ['Outside SLA.', 'Dominant cluster: trailing_slash'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 1,
            totalAffectedPages: 5449,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-03',
            latestSourceAgeDays: 13,
            sourceFreshnessStatus: 'blocking',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'trailing_slash',
            dominantEstimatedAffected: 3451.2,
          },
        },
        index: {
          label: 'Index Integrity',
          status: 'clear',
          summary: 'Index aligned.',
          target: 'Stay aligned.',
          observed: 'onlyInSitemap=0',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic Visibility',
          status: 'clear',
          summary: 'Traffic visible.',
          target: 'Stay visible.',
          observed: 'live-api',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: 'sc-domain:killer-skills.com',
            currentPeriod: { start: '2026-04-09', end: '2026-04-15' },
            previousPeriod: { start: '2026-04-02', end: '2026-04-08' },
            queryRows: 20,
            pageRows: 179,
            priorityQueryOpportunities: 0,
            priorityPageOpportunities: 0,
            queryPrecisionRisks: 0,
            currentPeriodAgeDays: 1,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI Runtime Posture',
          status: 'warning',
          summary: 'Backups need attention.',
          target: 'Stay free-only.',
          observed: 'workersAi=free-only',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 1,
            dailyRemaining: 59,
            runRemaining: 60,
            alertCount: 1,
            highestSeverity: 'warning',
          },
        },
        weeklyGates: [],
        nextActions: [
          'Ingest the newest Coverage Drilldown export(s) and rerun the coverage report.',
          'Keep the main-domain crawl loop running daily.',
        ],
      },
    });

    expect(report.overallStatus).toBe('active');
    expect(report.readyCount).toBeGreaterThan(0);
    expect(report.blockedCount).toBeGreaterThan(0);
    expect(report.watchCount).toBeGreaterThan(0);
    expect(report.items.some((item) => item.id === 'measurement-refresh-coverage-drilldown')).toBe(true);
    expect(report.items.some((item) => item.id === 'cluster-trailing_slash' && item.queueStatus === 'ready')).toBe(
      true,
    );
    expect(
      report.items.some((item) => item.id === 'watch-main-domain-crawl-health' && item.queueStatus === 'watch'),
    ).toBe(true);
  });

  it('maps page and query surfaces into metadata interventions', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'query-risk-example',
            lens: 'query',
            status: 'recoverable',
            score: 12,
            title: 'Query precision risk: example',
            summary: 'Weak intent.',
            evidence: ['5 impressions'],
            actions: ['Add explicit product-intent wording in title/meta.'],
          },
          {
            id: 'page-opportunity-example',
            lens: 'page',
            status: 'recoverable',
            score: 8,
            title: 'Page opportunity: example',
            summary: 'CTR gap.',
            evidence: ['CTR gap 4.50%'],
            actions: ['Test a tighter skill detail title template.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'warning',
          summary: 'warn',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 0,
            totalAffectedPages: 0,
            directories: [],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: null,
            dominantEstimatedAffected: null,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
    });

    const queryItem = report.items.find((item) => item.id === 'query-risk-example');
    const pageItem = report.items.find((item) => item.id === 'page-opportunity-example');

    expect(queryItem?.lane).toBe('metadata');
    expect(queryItem?.intervention).toBe('metadata-tightening');
    expect(queryItem?.queueStatus).toBe('ready');
    expect(pageItem?.lane).toBe('metadata');
    expect(pageItem?.queueStatus).toBe('ready');
  });

  it('turns the other cluster into a removal-execution batch when audit evidence exists', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-other',
            lens: 'cluster',
            status: 'recoverable',
            score: 9000,
            title: 'Issue cluster: other',
            summary: 'Mixed long-tail cluster.',
            evidence: ['other cluster sample'],
            actions: ['Review the other cluster against the freshest available raw Coverage Drilldown export.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'warning',
          summary: 'warn',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 0,
            totalAffectedPages: 0,
            directories: [],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: null,
            dominantEstimatedAffected: null,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: 'clear',
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      coverageOtherAudit: {
        totalRows: 514,
        sourceGeneratedAt: '2026-04-16T00:00:00.000Z',
        actionSummary: [
          { action: 'gone_410', count: 489 },
          { action: 'redirect_301', count: 20 },
          { action: 'observe', count: 5 },
        ],
        executionSummary: {
          exactRemoval410Count: 489,
          exactRemovalCoveredByRuntimeCount: 489,
          exactRemovalCoveredByRulesCount: 489,
          exactRemovalNeedsMaterializationCount: 0,
          redirectValidationCount: 20,
          redirectCoveredByRuntimeCount: 20,
          redirectCoveredByMiddlewareCount: 19,
          redirectCoveredByRulesCount: 1,
          redirectNeedsValidationCount: 0,
          observeCount: 5,
          manualReviewCount: 0,
        },
        reasonBreakdown: [
          { reason: 'blocked_by_sitemap', count: 274 },
          { reason: 'missing_from_sitemap_and_cache', count: 214 },
        ],
        nextActions: ['Keep 489 other-cluster URLs on the exact-removal / 410 track first.'],
      },
      missingClusterAudit: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        totalRows: 214,
        summary: {
          restore: 0,
          redirect: 0,
          redirectCoveredByMiddleware: 0,
          keep410: 214,
          manualReview: 0,
        },
        manualReviewBreakdown: [],
      },
    });

    const item = report.items.find((entry) => entry.id === 'cluster-other');
    expect(item).toBeTruthy();
    expect(item?.intervention).toBe('removal-execution');
    expect(item?.summary).toContain('489 exact-removal / 410');
    expect(item?.summary).toContain('blocked_by_sitemap (274)');
    expect(item?.action).toContain('Use reports/seo/latest-coverage-other-audit.csv as the operator list.');
    expect(item?.action).toContain('keep 20 runtime-covered redirects live');
    expect(item?.action).toContain('materialized_rule=1');
    expect(item?.action).toContain('214 missing_from_sitemap_and_cache rows stay on the keep-410 path');
  });

  it('turns source_file_path into a removal-execution batch when audit evidence exists', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-source_file_path',
            lens: 'cluster',
            status: 'recoverable',
            score: 6819.2,
            title: 'Issue cluster: source_file_path',
            summary: 'Source-file crawl trap cluster.',
            evidence: ['source-file cluster sample'],
            actions: [
              'Review the source_file_path cluster against the freshest available raw Coverage Drilldown export.',
            ],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 0,
            totalAffectedPages: 0,
            directories: [],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: null,
            dominantEstimatedAffected: null,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: 'clear',
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      sourceFileAudit: {
        totalRows: 372,
        sourceGeneratedAt: '2026-04-16T00:00:00.000Z',
        actionSummary: [
          { action: 'gone_410', count: 322 },
          { action: 'redirect_301', count: 50 },
        ],
        executionSummary: {
          exactRemoval410Count: 322,
          exactRemovalCoveredByRuntimeCount: 322,
          exactRemovalCoveredByRulesCount: 0,
          exactRemovalNeedsMaterializationCount: 0,
          redirectValidationCount: 50,
          redirectCoveredByRuntimeCount: 50,
          redirectCoveredByMiddlewareCount: 50,
          redirectCoveredByRulesCount: 0,
          redirectNeedsValidationCount: 0,
          observeCount: 0,
          manualReviewCount: 0,
        },
        reasonBreakdown: [
          { reason: 'crawl_trap_or_invalid_public_route', count: 322 },
          { reason: 'repo_single_skill_redirect', count: 47 },
          { reason: 'nested_skill_parent_redirect', count: 3 },
        ],
        nextActions: ['Keep 322 source-file URLs on the exact-removal / 410 track first.'],
      },
    });

    const item = report.items.find((entry) => entry.id === 'cluster-source_file_path');
    expect(item).toBeTruthy();
    expect(item?.intervention).toBe('removal-execution');
    expect(item?.summary).toContain('322 exact-removal / 410');
    expect(item?.summary).toContain('repo_single_skill_redirect (47)');
    expect(item?.action).toContain('Keep 50 runtime-covered redirects live');
    expect(item?.action).toContain('Use reports/seo/latest-coverage-source-file-audit.csv as the operator list.');
    expect(item?.evidence).toContain('sourceFileRows=372');
    expect(item?.evidence).toContain('redirectRuntimeCovered=50');
  });

  it('does not create a freshness blocker when coverage exports are already fresh', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'blocked',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'blocking',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'blocking',
          summary: 'Coverage has active issue clusters.',
          target: 't',
          observed: 'fresh export with issue buckets',
          notes: ['Dominant cluster: other'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 2,
            totalAffectedPages: 16232,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'other',
            dominantEstimatedAffected: 7146,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [
          'Work the dominant Coverage Drilldown clusters from `reports/seo/latest-coverage-drilldown.md`; current leader is other.',
        ],
      },
    });

    expect(report.items.some((item) => item.id === 'measurement-refresh-coverage-drilldown')).toBe(false);
  });

  it('promotes the other cluster into a ready diagnostic lane when a current other-audit exists', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-other',
            lens: 'cluster',
            status: 'recoverable',
            score: 8853.9,
            title: 'Issue cluster: other',
            summary: 'Dominant cluster still needs triage.',
            evidence: ['fresh coverage export', 'other cluster sample'],
            actions: ['Review the other cluster against the freshest available raw Coverage Drilldown export.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'warning',
          summary: 'coverage fresh and attributable',
          target: 't',
          observed: 'fresh raw export available',
          notes: ['Newest raw Coverage Drilldown export is 2026-04-16'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 1,
            totalAffectedPages: 10783,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'other',
            dominantEstimatedAffected: 5208.2,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      coverageOtherAudit: {
        totalRows: 483,
        sourceGeneratedAt: '2026-04-16T07:09:38.634Z',
        reasonBreakdown: [{ reason: 'blocked_by_sitemap', count: 274 }],
      },
      missingClusterAudit: {
        generatedAt: '2026-04-16T07:18:00.000Z',
        totalRows: 196,
        summary: {
          restore: 5,
          redirect: 29,
          keep410: 155,
          manualReview: 7,
        },
      },
    });

    const otherItem = report.items.find((item) => item.id === 'cluster-other');
    expect(otherItem?.queueStatus).toBe('ready');
    expect(otherItem?.blockedBy).toEqual([]);
    expect(otherItem?.summary).toContain('196');
    expect(otherItem?.action).toContain('155');
    expect(otherItem?.action).toContain('29');
    expect(otherItem?.action).toContain('5');
    expect(otherItem?.evidence).toContain('keep410=155');
  });

  it('omits zero-count redirect and restore wording for the missing-cluster split', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-other',
            lens: 'cluster',
            status: 'recoverable',
            score: 8853.9,
            title: 'Issue cluster: other',
            summary: 'Dominant cluster still needs triage.',
            evidence: ['fresh coverage export', 'other cluster sample'],
            actions: ['Review the other cluster against the freshest available raw Coverage Drilldown export.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'warning',
          summary: 'coverage fresh and attributable',
          target: 't',
          observed: 'fresh raw export available',
          notes: ['Newest raw Coverage Drilldown export is 2026-04-16'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 1,
            totalAffectedPages: 10783,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'other',
            dominantEstimatedAffected: 5208.2,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      coverageOtherAudit: {
        totalRows: 483,
        sourceGeneratedAt: '2026-04-16T07:09:38.634Z',
        reasonBreakdown: [{ reason: 'blocked_by_sitemap', count: 274 }],
      },
      missingClusterAudit: {
        generatedAt: '2026-04-16T07:18:00.000Z',
        totalRows: 188,
        summary: {
          restore: 0,
          redirect: 0,
          keep410: 177,
          manualReview: 11,
        },
        manualReviewBreakdown: [
          { workstream: 'promote_noindex_target', count: 4, summary: 'single target still noindex' },
          { workstream: 'resolve_multi_skill_repo_root', count: 6, summary: 'repo root maps to many raw skills' },
          { workstream: 'resolve_route_mismatch', count: 1, summary: 'slug mismatch' },
        ],
      },
    });

    const otherItem = report.items.find((item) => item.id === 'cluster-other');
    expect(otherItem?.action).toContain('keep 177 missing samples at 410');
    expect(otherItem?.action).toContain('manually review 11 remaining samples');
    expect(otherItem?.action).not.toContain('validate 0');
    expect(otherItem?.action).not.toContain('restore 0');
    expect(otherItem?.action).toContain('4 noindex-promotion cases');
    expect(otherItem?.action).toContain('6 multi-skill repo-root cases');
    expect(otherItem?.action).toContain('1 route-mismatch cases');
    expect(otherItem?.summary).toContain('177 should stay 410');
    expect(otherItem?.summary).not.toContain('redirect candidates');
    expect(otherItem?.summary).not.toContain('should be restored');
    expect(otherItem?.evidence).toContain(
      'manualReviewWorkstreams=4 noindex-promotion cases; 6 multi-skill repo-root cases; 1 route-mismatch cases',
    );
  });

  it('switches the follow-up copy to keep-410 confirmation when manual review is exhausted', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-other',
            lens: 'cluster',
            status: 'recoverable',
            score: 13066.5,
            title: 'Issue cluster: other',
            summary: 'Dominant cluster still needs triage.',
            evidence: ['fresh coverage export', 'other cluster sample'],
            actions: ['Review the other cluster against the freshest available raw Coverage Drilldown export.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'warning',
          summary: 'coverage fresh and attributable',
          target: 't',
          observed: 'fresh raw export available',
          notes: ['Newest raw Coverage Drilldown export is 2026-04-16'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 1,
            totalAffectedPages: 10783,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'other',
            dominantEstimatedAffected: 5208.2,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },

        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      coverageOtherAudit: {
        totalRows: 514,
        sourceGeneratedAt: '2026-04-16T07:09:38.634Z',
        reasonBreakdown: [{ reason: 'missing_from_sitemap_and_cache', count: 214 }],
      },
      missingClusterAudit: {
        generatedAt: '2026-04-17T08:18:00.000Z',
        totalRows: 214,
        summary: {
          restore: 0,
          redirect: 0,
          keep410: 214,
          manualReview: 0,
        },
        manualReviewBreakdown: [],
      },
    });

    const otherItem = report.items.find((item) => item.id === 'cluster-other');
    expect(otherItem?.action).toContain('keep 214 missing samples at 410');
    expect(otherItem?.action).toContain('confirm the keep-410 rationale');
    expect(otherItem?.action).not.toContain('remaining manual-review cases');
  });

  it('distinguishes middleware-covered redirects from explicit 301 work', () => {
    const report = buildRecoveryExecutionQueueReport({
      controlBoard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'recoverable',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        trafficSourceMode: 'live-api',
        headline: 'Control board headline',
        lenses: [],
        items: [
          {
            id: 'cluster-other',
            lens: 'cluster',
            status: 'recoverable',
            score: 8853.9,
            title: 'Issue cluster: other',
            summary: 'Dominant cluster still needs triage.',
            evidence: ['fresh coverage export', 'other cluster sample'],
            actions: ['Review the other cluster against the freshest available raw Coverage Drilldown export.'],
          },
        ],
        nextActions: [],
      },
      scorecard: {
        generatedAt: '2026-04-16T00:00:00.000Z',
        overallStatus: 'warning',
        technicalRecoveryStatus: 'clear',
        businessRecoveryStatus: 'warning',
        headline: 'Scorecard headline',
        crawl: {
          label: 'Crawl Health',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'crawl.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            checkedUrls: 0,
            discoveredUrls: 0,
            sitemapFiles: 0,
            sitemapErrors: 0,
            status2xx: 0,
            status3xx: 0,
            status4xx: 0,
            status5xx: 0,
            statusOther: 0,
            cloudflare1102: 0,
            flakyRecovered: 0,
            flakyRecoveredRate: 0,
            fourXxRate: 0,
          },
        },
        coverage: {
          label: 'Coverage Drilldown',
          status: 'warning',
          summary: 'coverage fresh and attributable',
          target: 't',
          observed: 'fresh raw export available',
          notes: ['Newest raw Coverage Drilldown export is 2026-04-16'],
          source: {
            path: 'coverage.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            issueCount: 1,
            totalAffectedPages: 10783,
            directories: ['/tmp/coverage'],
            latestSourceDate: '2026-04-16',
            latestSourceAgeDays: 0,
            sourceFreshnessStatus: 'fresh',
            sourcePreferredWindowDays: 3,
            sourceMaxWindowDays: 7,
            dominantCluster: 'other',
            dominantEstimatedAffected: 5208.2,
          },
        },
        index: {
          label: 'Index',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'index.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: { onlyInSitemap: 0, onlyInIndexableCache: 0, totalDrift: 0 },
        },
        traffic: {
          label: 'Traffic',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'traffic.md',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            status: 'clear',
            sourceMode: 'live-api',
            site: null,
            currentPeriod: null,
            previousPeriod: null,
            queryRows: null,
            pageRows: null,
            priorityQueryOpportunities: null,
            priorityPageOpportunities: null,
            queryPrecisionRisks: null,
            currentPeriodAgeDays: null,
            failureReason: null,
            nextStep: null,
          },
        },
        aiPosture: {
          label: 'AI',
          status: 'clear',
          summary: 'clear',
          target: 't',
          observed: 'o',
          notes: [],
          source: {
            path: 'ai.json',
            exists: true,
            generatedAt: '2026-04-16T00:00:00.000Z',
            ageDays: 0,
            freshness: 'fresh',
          },
          metrics: {
            workersAiMode: 'free-only',
            fallbackPolicy: 'cold',
            backupPostures: {},
            maxCallsPerRun: 60,
            maxCallsPerDay: 60,
            dailyCalls: 0,
            dailyRemaining: 60,
            runRemaining: 60,
            alertCount: 0,
            highestSeverity: null,
          },
        },
        weeklyGates: [],
        nextActions: [],
      },
      coverageOtherAudit: {
        totalRows: 483,
        sourceGeneratedAt: '2026-04-16T07:09:38.634Z',
        reasonBreakdown: [{ reason: 'blocked_by_sitemap', count: 274 }],
      },
      missingClusterAudit: {
        generatedAt: '2026-04-16T07:18:00.000Z',
        totalRows: 188,
        summary: {
          restore: 0,
          redirect: 3,
          redirectCoveredByMiddleware: 3,
          keep410: 177,
          manualReview: 8,
        },
        manualReviewBreakdown: [
          { workstream: 'promote_noindex_target', count: 1, summary: 'single target still noindex' },
          { workstream: 'resolve_multi_skill_repo_root', count: 6, summary: 'repo root maps to many raw skills' },
          { workstream: 'resolve_route_mismatch', count: 1, summary: 'slug mismatch' },
        ],
      },
    });

    const otherItem = report.items.find((item) => item.id === 'cluster-other');
    expect(otherItem?.action).toContain('verify 3 middleware-covered repo-root redirects after deploy');
    expect(otherItem?.action).not.toContain('validate 3 explicit 301 candidates');
    expect(otherItem?.summary).toContain('3 are redirect candidates (3 already covered by middleware)');
    expect(otherItem?.evidence).toContain('redirectCoveredByMiddleware=3');
  });
});
