#!/usr/bin/env node --import tsx
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { resolveConfig, format } from 'prettier';
import { authoritySurfacePublicCopy } from '../src/lib/authority-surface-public-copy';

type Manifest = {
  surfaces: Array<{
    id: string;
    role: string;
    tier: string;
    surfaceClass: string;
    href: string;
    placements: string[];
  }>;
};

const ROOT = process.cwd();
const MANIFEST_PATH = resolve(ROOT, 'data/authority-surfaces.json');
const OUTPUT_PATH = resolve(ROOT, 'src/lib/authority-surface-public-data.ts');

function readManifest(): Manifest {
  const parsed = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest;
  if (!parsed || !Array.isArray(parsed.surfaces)) {
    throw new Error(`FATAL: manifest missing or malformed at ${MANIFEST_PATH}`);
  }
  return parsed;
}

const publicCopy = authoritySurfacePublicCopy;

function renderSurface(s: Manifest['surfaces'][number]): string {
  const copy = publicCopy[s.id];
  if (!copy) {
    throw new Error(
      `Surface ${s.id} missing from authoritySurfacePublicCopy. Add hand-authored copy in src/lib/authority-surface-public-copy.ts.`,
    );
  }
  const placements = `[${s.placements.map((p) => `'${p}'`).join(', ')}]`;
  return [
    `    {`,
    `      id: '${s.id}',`,
    `      role: '${s.role}',`,
    `      tier: '${s.tier}',`,
    `      surfaceClass: '${s.surfaceClass}',`,
    `      href: '${s.href}',`,
    `      title: { en: ${JSON.stringify(copy.title.en)}, zh: ${JSON.stringify(copy.title.zh)} },`,
    `      description: { en: ${JSON.stringify(copy.description.en)}, zh: ${JSON.stringify(copy.description.zh)} },`,
    `      placements: ${placements},`,
    `    },`,
  ].join('\n');
}

async function main() {
  const manifest = readManifest();
  const head = [
    `// AUTO-GENERATED by scripts/sync-authority-surface-public-data.ts — DO NOT EDIT.`,
    `// Structural fields come from data/authority-surfaces.json; user-facing copy is`,
    `// hand-authored in src/lib/authority-surface-public-copy.ts.`,
    `// Regenerate with: npm run sync:authority-surfaces`,
    ``,
    `export const authoritySurfacePublicData = {`,
    `  surfaces: [`,
  ].join('\n');
  const body = manifest.surfaces.map(renderSurface).join('\n');
  const tail = `\n  ],\n} as const;\n`;
  const raw = head + '\n' + body + '\n' + tail;

  // Format through the repo's prettier config so the emitted bytes match what the
  // pre-commit hook (lint-staged -> prettier --write) produces. Without this, the
  // CI guard (sync then git diff --exit-code) would fail because lint-staged
  // rewrites the generator's raw double-quoted single-line output into the
  // prettier-friendly single-quoted, width-wrapped form on commit.
  const config = (await resolveConfig(OUTPUT_PATH)) ?? {};
  const formatted = await format(raw, { ...config, parser: 'typescript' });
  writeFileSync(OUTPUT_PATH, formatted);
  console.log(`Wrote ${OUTPUT_PATH} (${manifest.surfaces.length} surfaces)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
